### ISSUE TITLE
Error: write EPIPE on Heroku

### ISSUE THREAD

**Issue by tiefenb** [alevy/memjs#65]
I have an application which works fine with local memcached. But on heroku with MemCachier I always get this error:

The file is under 1MB so I don't have any idea...

With node 0.12.7 and iojs 3.0.0

2015-08-14T09:58:23.326274+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T09:58:23.326348+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T09:58:23.326410+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T09:58:23.326450+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T09:58:23.325681+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T09:58:23.326497+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T09:58:23.340426+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T09:58:23.344439+00:00 app[web.1]: memjs error: { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
2015-08-14T09:58:23.345524+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T09:58:23.346038+00:00 app[web.1]: memjs error: { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
2015-08-14T09:58:23.352236+00:00 app[web.1]: Debug: internal, implementation, error 
2015-08-14T09:58:23.352240+00:00 app[web.1]:     SyntaxError: Uncaught error: Unexpected end of input
2015-08-14T09:58:23.352243+00:00 app[web.1]:     at Object.parse (native)
2015-08-14T09:58:23.352245+00:00 app[web.1]:     at /app/tariffs/index.js:22:20
2015-08-14T09:58:23.352246+00:00 app[web.1]:     at /app/node_modules/memjs/lib/memjs/memjs.js:143:19
2015-08-14T09:58:23.352248+00:00 app[web.1]:     at Object.errorHandler (/app/node_modules/memjs/lib/memjs/memjs.js:504:21)
2015-08-14T09:58:23.352250+00:00 app[web.1]:     at Server.error (/app/node_modules/memjs/lib/memjs/server.js:54:16)
2015-08-14T09:58:23.352252+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/memjs/lib/memjs/server.js:119:12)
2015-08-14T09:58:23.352253+00:00 app[web.1]:     at Socket.emit (events.js:107:17)
2015-08-14T09:58:23.352255+00:00 app[web.1]:     at onwriteError (_stream_writable.js:317:10)
2015-08-14T09:58:23.352257+00:00 app[web.1]:     at onwrite (_stream_writable.js:335:5)
2015-08-14T09:58:23.352258+00:00 app[web.1]:     at WritableState.onwrite (_stream_writable.js:105:5)

**Comment by tiefenb** [comment]
The error came from parsing an invalid json... not memjs

**Comment by tiefenb** [comment]
after fixing an other bug, I have already this issue...

**Comment by tiefenb** [comment]
2015-08-14T11:09:59.345587+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.346372+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.346447+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.346650+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.346722+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.354675+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.358820+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.358822+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.358823+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.358824+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.358826+00:00 app[web.1]:   address: undefined } string
2015-08-14T11:09:59.360061+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.361678+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.361681+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.361683+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.361684+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.361686+00:00 app[web.1]:   address: undefined } string
2015-08-14T11:09:59.346188+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.357766+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.362441+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.362613+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.362618+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.357769+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.362615+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.362619+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.357772+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.358500+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.360223+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.357771+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.357774+00:00 app[web.1]:   address: undefined } string
2015-08-14T11:09:59.362620+00:00 app[web.1]:   address: undefined } string
2015-08-14T11:09:59.363062+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.400027+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.399945+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.400115+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.399768+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.399849+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.433272+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.434755+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.360225+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.360226+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.363223+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.360227+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.399598+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.360229+00:00 app[web.1]:   address: undefined } string
2015-08-14T11:09:59.361044+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.433526+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.363225+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.433532+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.363229+00:00 app[web.1]:   address: undefined } string
2015-08-14T11:09:59.435309+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.433529+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.433531+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.434757+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.434759+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.434762+00:00 app[web.1]:   address: undefined } string
2015-08-14T11:09:59.435481+00:00 app[web.1]:   address: undefined } string
2015-08-14T11:09:59.363226+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.363227+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.434760+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.435474+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.435478+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.434122+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.434127+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.434124+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.434125+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.433534+00:00 app[web.1]:   address: undefined } string
2015-08-14T11:09:59.433743+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.434128+00:00 app[web.1]:   address: undefined } string
2015-08-14T11:09:59.434605+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.435477+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.435479+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.436014+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.436171+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.436173+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.436169+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.436172+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.436175+00:00 app[web.1]:   address: undefined } string
2015-08-14T11:09:59.436343+00:00 app[web.1]: MemJS: Server <mc2.dev.eu.ec2.memcachier.com:11211> failed after (2) retries with error - write EPIPE
2015-08-14T11:09:59.436484+00:00 app[web.1]: memjs error: { [Error: write EPIPE]
2015-08-14T11:09:59.436486+00:00 app[web.1]:   code: 'EPIPE',
2015-08-14T11:09:59.436504+00:00 app[web.1]:   syscall: 'write',
2015-08-14T11:09:59.436492+00:00 app[web.1]:   errno: 'EPIPE',
2015-08-14T11:09:59.436505+00:00 app[web.1]:   address: undefined } string

**Comment by alevy** [comment]
The first case, it seems like there was/is a bug in the closure used for error handling by your app (at `/app/tariffs/index.js:22:20`). It looks like it's passing something to `Object.parse` that doesn't parse as expected.

In the second case, it seems like much of the output is generated by your app (potentially the error handling closure?). It's hard to tell from there what's going on, are you able to paste your error handler here?

**Comment by tiefenb** [comment]
Hi, sure here is my caching function. which checks if some company-idxyc exists, when not load it from the file system and save in in memcached for 12 hours...

input.getCompany = function(id, callback) {
		memcached.get('company-'+id, function (err, company) {
		  if(!err && company) {
		  	company = JSON.parse(company);
		  	callback(company);
		  } else {
		  	fs.readFile(__dirname + '/../companies/'+id+'.json', { "encoding": "utf-8" }, function(err, data) {
				if(err || !data) { console.log('Error loading company json:', id); return callback(undefined); }
		  		memcached.set('company-'+id, data, function(err, val) {
		  			if(err) { console.log('memjs error:', err, typeof data); }
		  			try { data = JSON.parse(data) } catch(err) { console.log('parse error', id); }
		  			callback(data);
				}, 43200); // 12 hours in sec.

		  	});
		  }
		});
	};

**Comment by danieler1981** [comment]
in me case this issue was caused by multiple 'set' that was coming at short time on the same key.

I was able to resolve by blocking my flow and waiting for 'set' answer before accepting new 'get' or 'set' on that key.

memjs.set(theKey, theValue, function (err, result) {
    // now the flow can move ahead
});

**Comment by dterei** [comment]
Fixed.
